# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodecommitSign < Formula
  desc "Generate a signed AWS V4 CodeCommit URL directly from an IAM role. No dedicated CodeCommit credentials needed"
  homepage "https://github.com/gembaadvantage/codecommit-sign"
  version "1.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/codecommit-sign/releases/download/v1.1.0/codecommit-sign_1.1.0_darwin-x86_64.tar.gz"
      sha256 "6824b5d13a5e6078a9c2961dd25fef09e8ec8a813d9e7a37298b390c97ed65ff"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gembaadvantage/codecommit-sign/releases/download/v1.1.0/codecommit-sign_1.1.0_darwin-arm64.tar.gz"
      sha256 "3914dbbe6b1bf5f2afafbc5510bfbcf71301bed592694d476bd3e02c40d288da"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/codecommit-sign/releases/download/v1.1.0/codecommit-sign_1.1.0_linux-x86_64.tar.gz"
      sha256 "b31aae387e629fc66018fc6a4c91d4ace29777d544911d5524c33aff1ef1b17c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gembaadvantage/codecommit-sign/releases/download/v1.1.0/codecommit-sign_1.1.0_linux-arm64.tar.gz"
      sha256 "b0c139860954f2aa96cf38362b2150172f702d2c1f7bc5dea7a4c55f0dbcaed6"
    end
  end

  def install
    bin.install "codecommit-sign"

    bash_output = Utils.safe_popen_read(bin/"codecommit-sign", "completion", "bash")
    (bash_completion/"codecommit-sign").write bash_output

    zsh_output = Utils.safe_popen_read(bin/"codecommit-sign", "completion", "zsh")
    (zsh_completion/"_codecommit-sign").write zsh_output

    fish_output = Utils.safe_popen_read(bin/"codecommit-sign", "completion", "fish")
    (fish_completion/"codecommit-sign.fish").write fish_output
  end

  test do
    installed_version = shell_output("#{bin}/codecommit-sign version --short 2>&1")
    assert_match "v#{version}", installed_version
  end
end
