# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitRemoteCodecommit < Formula
  desc "A git remote helper that removes the need for dedicated CodeCommit user credentials"
  homepage "https://github.com/gembaadvantage/git-remote-codecommit"
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.0/git-remote-codecommit_v1.0.0_darwin-x86_64.tar.gz"
      sha256 "e2a44274e7c056a1ed33db7571fb4a5a2f64aad4e0d94d6dfe22e84b5480bdbb"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.0/git-remote-codecommit_v1.0.0_darwin-arm64.tar.gz"
      sha256 "58f4d0a02906060b41b7aabbc85491129bbd84cf22a882f16f451db215dc1e61"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.0/git-remote-codecommit_v1.0.0_linux-x86_64.tar.gz"
      sha256 "87f13572fe9cfc33bae887a2db1af466d140037078dbfd27d833fc23f9593617"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.0/git-remote-codecommit_v1.0.0_linux-arm64.tar.gz"
      sha256 "cbc262740b9ebdbeff1eec53dcf521e99e33909c8a41cf73adc2f876979731fa"
    end
  end

  def install
    bin.install "git-remote-codecommit"
  end

  test do
    installed_version = shell_output("#{bin}/git-remote-codecommit version --short 2>&1")
    assert_match "v#{version}", installed_version
  end
end
