# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitRemoteCodecommit < Formula
  desc "A git remote helper that removes the need for dedicated CodeCommit user credentials"
  homepage "https://github.com/gembaadvantage/git-remote-codecommit"
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.0/git-remote-codecommit_v1.0.0_darwin-x86_64.tar.gz"
      sha256 "10005ea9d74a8275101446834cd25350099b2d86ab47b7781669ef36f3cea21f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.0/git-remote-codecommit_v1.0.0_darwin-arm64.tar.gz"
      sha256 "915a5990e0cc54b05b448da5c262e1af6f6d7ebbb905f6a64ece4b879155c740"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.0/git-remote-codecommit_v1.0.0_linux-x86_64.tar.gz"
      sha256 "ebfe879aed518950e21c06c0b92b17be3fb1e1f5f4c7d78e492aa0dcc99c94bd"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.0/git-remote-codecommit_v1.0.0_linux-arm64.tar.gz"
      sha256 "0878b350c8853f78b36e1d7c58a226d878316c569ec4714746935b696488f451"
    end
  end

  def install
    bin.install "git-remote-codecommit"
  end

  test do
    installed_version = shell_output("#{bin}/git-remote-codecommit version --short 2>&1")
    assert_match "v#{version}", installed_version
  end
end
