# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitRemoteCodecommit < Formula
  desc "A git remote helper that removes the need for dedicated CodeCommit user credentials"
  homepage "https://github.com/gembaadvantage/git-remote-codecommit"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.1/git-remote-codecommit_v1.0.1_darwin-x86_64.tar.gz"
      sha256 "b7a0f979c13f3b05bcf6f57d80a9e8683c31d9834b703aa9f3f1b45c33b0e814"

      def install
        bin.install "git-remote-codecommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.1/git-remote-codecommit_v1.0.1_darwin-arm64.tar.gz"
      sha256 "b54201429a468ca425158ae81fbd42b9fd2a732211b33f93e2c9891a07b26a65"

      def install
        bin.install "git-remote-codecommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.1/git-remote-codecommit_v1.0.1_linux-x86_64.tar.gz"
      sha256 "f9025ca5e94c487949791f967f7887393c4d2cd497bc4c4f692310ba75945262"

      def install
        bin.install "git-remote-codecommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gembaadvantage/git-remote-codecommit/releases/download/v1.0.1/git-remote-codecommit_v1.0.1_linux-arm64.tar.gz"
      sha256 "ccd2eeb10a0bf69aaf9a1abf3c540aca1bc53d2821e8ec2043f556b5c2f2953a"

      def install
        bin.install "git-remote-codecommit"
      end
    end
  end

  test do
    installed_version = shell_output("#{bin}/git-remote-codecommit version --short 2>&1")
    assert_match "v#{version}", installed_version
  end
end
