# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uplift < Formula
  desc "Semantic versioning the easy way"
  homepage "https://github.com/gembaadvantage/uplift"
  version "0.6.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/uplift/releases/download/v0.6.0/uplift_0.6.0_darwin-x86_64.tar.gz"
      sha256 "39c8fa18fea360000b07b005d019ca9aa403b9460c124c2aba3d80ff5cfad769"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gembaadvantage/uplift/releases/download/v0.6.0/uplift_0.6.0_darwin-arm64.tar.gz"
      sha256 "7afe047646a7c03e04487eef815e2584395ed0de9ab778068b16b6917f9c3e0c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gembaadvantage/uplift/releases/download/v0.6.0/uplift_0.6.0_linux-x86_64.tar.gz"
      sha256 "7b5f0a0d3cdd7eb7291710fa08890fd700bdcdee47ed2efbef63cfb4b9160fe6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gembaadvantage/uplift/releases/download/v0.6.0/uplift_0.6.0_linux-arm64.tar.gz"
      sha256 "3dcebf95edeb8aa4c3162a30d448521e9a8044c85407de343633f9c4fdd00f84"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "uplift"

    bash_output = Utils.safe_popen_read(bin/"uplift", "completion", "bash")
    (bash_completion/"uplift").write bash_output

    zsh_output = Utils.safe_popen_read(bin/"uplift", "completion", "zsh")
    (zsh_completion/"_uplift").write zsh_output

    fish_output = Utils.safe_popen_read(bin/"uplift", "completion", "fish")
    (fish_completion/"uplift.fish").write fish_output
  end

  test do
    installed_version = shell_output("#{bin}/uplift version --short 2>&1")
    assert_match "v#{version}", installed_version
  end
end
